apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypercloud-webhook
  namespace: hypercloud5-system
  labels:
    hypercloud: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      hypercloud: webhook
  template:
    metadata:
      labels:
        hypercloud: webhook
    spec:
      containers:
      - name: hypercloud-webhook
        image: tmaxcloudck/hypercloud-webhook:b5.0.2.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
           memory: "1Gi"
           cpu: "500m"
          limits:
           memory: "1Gi"
           cpu: "500m"
        env:
        - name: TZ
          value: "Asia/Seoul"
        - name: SIDECAR_IMAGE
          value: "fluent/fluent-bit:1.5-debug"
        ports:
        - containerPort: 8443
          name: webhook 
        volumeMounts:
        - name: hypercloud-webhook-certs
          mountPath: /run/secrets/tls
          readOnly: true
      volumes:
      - name: hypercloud-webhook-certs
        secret:
          secretName: hypercloud-webhook-certs
        name: hypercloud-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: hypercloud-webhook-svc
  namespace: hypercloud5-system
spec:
  type: NodePort
  selector:
    hypercloud: webhook
  ports:
    - port: 443
      targetPort: webhook
